language: ruby

rvm:
 - 2.6.5

addons:
  chrome: stable
  postgresql: "9.5"

env:
  global:
    - BUNDLE_GEMFILE="$TRAVIS_BUILD_DIR/Gemfile"
    - BUNDLE_PATH="$HOME/.bundle"
  matrix:
    - GEM=. DB=postgres

before_script:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

script:
  - cd $GEM;
  - bundle exec rake test_app
  - SIMPLECOV=1 CODECOV=1 bundle exec rake
